version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      timezone: "Australia/Sydney"
    target-branch: "develop"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      timezone: "Australia/Sydney"
    target-branch: "develop"

  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      timezone: "Australia/Sydney"
    target-branch: "develop"
