disabled_rules:
  - line_length
  - redundant_optional_initialization

opt_in_rules:
  - missing_docs

included:

excluded:
  .build

trailing_comma:
  mandatory_comma: true

vertical_whitespace:
  max_empty_lines: 2
