language: swift
os: osx
osx_image: xcode9.3

install: gem install xcpretty

jobs:
  include:
    - script:
      - xcodebuild test -project URITemplate.xcodeproj -scheme URITemplate-ios -destination "platform=iOS Simulator,name=iPhone X"  | xcpretty -c && exit ${PIPESTATUS[0]}
    - script:
      - xcodebuild test -project URITemplate.xcodeproj -scheme URITemplate-mac -destination "platform=macos"  | xcpretty -c && exit ${PIPESTATUS[0]}
    - script:
      - xcodebuild test -project URITemplate.xcodeproj -scheme URITemplate-tv -destination "platform=tvOS Simulator,name=Apple TV 4K"  | xcpretty -c && exit ${PIPESTATUS[0]}
    - script:
      - xcodebuild build -project URITemplate.xcodeproj -scheme URITemplate-watch | xcpretty -c && exit ${PIPESTATUS[0]}
