language: swift
os: osx
osx_image: xcode12.2

install: gem install xcpretty

jobs:
  include:
    - script:
      - set -o pipefail && xcodebuild test -project URITemplate.xcodeproj -scheme URITemplateTests-ios -destination "platform=iOS Simulator,name=iPhone 12"  | xcpretty -c
      - bash <(curl -s https://codecov.io/bash) -J Tests-ios -F ios
    - script:
      - set -o pipefail && xcodebuild test -project URITemplate.xcodeproj -scheme URITemplateTests-mac -destination "platform=macos"  | xcpretty -c
      - bash <(curl -s https://codecov.io/bash) -J Tests-mac -F mac
    - script:
      - set -o pipefail && xcodebuild test -project URITemplate.xcodeproj -scheme URITemplateTests-tv -destination "platform=tvOS Simulator,name=Apple TV 4K"  | xcpretty -c
      - bash <(curl -s https://codecov.io/bash) -J Tests-tv -F tv
    - script:
      - set -o pipefail && xcodebuild build -project URITemplate.xcodeproj -scheme URITemplate-watch | xcpretty -c
