name: CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage
    - name: Prepare coverage file
      run: xcrun llvm-cov export -format="lcov" .build/debug/ScreamURITemplatePackageTests.xctest/Contents/MacOS/ScreamURITemplatePackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        fail_ci_if_error: true
        verbose: true

  build-5_4_2:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Check Swift version
      run: |
        sudo xcode-select -s /Applications/Xcode_12.5.1.app/
        export TOOLCHAINS=swift
        swift --version
    - name: Run tests
      run: swift test
