name: Lint

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  SwiftFormat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: irgaly/setup-mint@v1
    - name: SwiftFormat Lint
      run: mint run swiftformat --lint .
