name: Lint
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - uses: irgaly/setup-mint@v1
    - name: SwiftLint
      run: mint run swiftlint --strict
  SwiftFormat:
    runs-on: macos-latest
    needs: SwiftLint
    steps:
    - uses: actions/checkout@v6
    - uses: irgaly/setup-mint@v1
    - name: SwiftFormat Lint
      run: mint run swiftformat --lint .
  Docc:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.1.app/Contents/Developer
    steps:
    - uses: actions/checkout@v6
    - name: Swift-Docc Validate
      run: swift package generate-documentation --target ScreamURITemplate --target ScreamURITemplateMacros --analyze --warnings-as-errors
