name: Lint

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  SwiftLint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: irgaly/setup-mint@v1
    - name: SwiftLint
      run: mint run swiftlint --strict
  SwiftFormat:
    runs-on: macos-latest
    needs: SwiftLint
    steps:
    - uses: actions/checkout@v4
    - uses: irgaly/setup-mint@v1
    - name: SwiftFormat Lint
      run: mint run swiftformat --lint .
