name: SwiftLint

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: SwiftLint Strict
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict
